
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    mem_limit: 2GB

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: backend:8080
    ports:
      - "80:80"
    mem_limit: 256MB
    env_file:
      - ./frontend/.env